"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import "./bate-ponto.css";

type Colab={id:string;nome:string;status:string};
type Ponto={id:string;colaboradora_id:string;jornada_id?:string|null;data:string;entrada:string;saida_almoco:string;retorno_almoco:string;saida:string;falta:boolean;tipo_dia?:string|null;observacao:string};
const hoje=()=>new Date().toISOString().slice(0,10), mes=()=>hoje().slice(0,7);
const mins=(v:string)=>{if(!v||!v.includes(":"))return 0;const[h,m]=v.split(":").map(Number);return h*60+m};
const hm=(v:number)=>{const s=v<0?"-":"";v=Math.abs(Math.round(v));return `${s}${Math.floor(v/60)}h${String(v%60).padStart(2,"0")}`};
const fimSemana=(d:string)=>[0,6].includes(new Date(`${d}T12:00:00`).getDay());
const sabado=(d:string)=>new Date(`${d}T12:00:00`).getDay()===6;
const br=(d:string)=>d?d.split("-").reverse().join("/"):"—";
const numBR=(v:string)=>Number(String(v||"0").replace(/\./g,"").replace(",","."))||0;
const moeda=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const nomesDias=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
const diasDoMes=(ym:string)=>{const [ano,mesN]=ym.split("-").map(Number);if(!ano||!mesN)return[];const qtd=new Date(ano,mesN,0).getDate();return Array.from({length:qtd},(_,i)=>{const d=`${ano}-${String(mesN).padStart(2,"0")}-${String(i+1).padStart(2,"0")}`;return{data:d,dia:nomesDias[new Date(`${d}T12:00:00`).getDay()]}})};

export default function ControlePontoRH({colaboradoras}:{colaboradoras:Colab[]}){
 const sb=useMemo(()=>createClient(),[]),[pontos,setPontos]=useState<Ponto[]>([]);
 type Jornada={id:string;nome:string;entrada:string;saidaAlmoco:string;retornoAlmoco:string;saida:string;carga:number;tolEntrada:number;tolSaida:number};
 const[jornadas,setJornadas]=useState<Jornada[]>([]);
 const[jornadaId,setJornadaId]=useState("");
 const[cfg,setCfg]=useState({nome:"Jornada 08:30",entrada:"08:30",saidaAlmoco:"12:00",retornoAlmoco:"13:30",saida:"18:00",carga:480,tolEntrada:5,tolSaida:5});
 const[mesRef,setMesRef]=useState(mes()),[pessoa,setPessoa]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<string|null>(null),[msg,setMsg]=useState("");
 const[abaPonto,setAbaPonto]=useState<"registrar"|"espelho">("registrar"),[modalJornada,setModalJornada]=useState(false);
 const[vinculos,setVinculos]=useState<{colaboradora_id:string;jornada_id:string}[]>([]),[modalEquipe,setModalEquipe]=useState(false),[jornadaEquipe,setJornadaEquipe]=useState<Jornada|null>(null),[selecionados,setSelecionados]=useState<string[]>([]);
 const[modalJornadas,setModalJornadas]=useState(false);
 const[valorHora,setValorHora]=useState("7,71"),[adicionalSabado,setAdicionalSabado]=useState("50");
 const[modalFechamento,setModalFechamento]=useState(false);
 const[fechamentos,setFechamentos]=useState<any[]>([]);
 const[f,setF]=useState({colaboradora_id:"",jornada_id:"",data:hoje(),entrada:"08:30",saida_almoco:"12:00",retorno_almoco:"13:30",saida:"18:00",falta:false,tipo_dia:"normal",observacao:""});

 async function carregar(){
  const[a,b,c,d]=await Promise.all([sb.from("rh_ponto").select("*").order("data",{ascending:false}),sb.from("rh_jornadas").select("*").order("nome"),sb.from("rh_jornada_colaboradoras").select("*"),sb.from("rh_fechamento_ponto").select("*").order("criado_em",{ascending:false})]);
  if(a.error||b.error||c.error||d.error){setMsg((a.error||b.error||c.error||d.error)!.message);return}
  setVinculos((c.data||[]).map((x:any)=>({colaboradora_id:String(x.colaboradora_id),jornada_id:String(x.jornada_id)}))); setFechamentos(d.data||[]);
  setPontos((a.data||[]) as Ponto[]);
  const js=(b.data||[]).map((c:any)=>({id:String(c.id),nome:String(c.nome),entrada:String(c.entrada).slice(0,5),saidaAlmoco:String(c.saida_almoco).slice(0,5),retornoAlmoco:String(c.retorno_almoco).slice(0,5),saida:String(c.saida).slice(0,5),carga:Number(c.carga_diaria_min||480),tolEntrada:Number(c.tolerancia_entrada_min??5),tolSaida:Number(c.tolerancia_saida_min??5)}));
  setJornadas(js); if(!jornadaId&&js[0])setJornadaId(js[0].id);
 }
 useEffect(()=>{void carregar()},[]);
 const trab=(p:Ponto)=>p.falta||["feriado","folga","atestado"].includes(p.tipo_dia||"")?0:Math.max(0,mins(p.saida_almoco)-mins(p.entrada))+Math.max(0,mins(p.saida)-mins(p.retorno_almoco));
 const jornadaDo=(p:Ponto)=>jornadas.find(j=>j.id===p.jornada_id)||jornadas[0]||cfg;
 const extraDia=(p:Ponto)=>{const j=jornadaDo(p);if(p.falta||["feriado","folga","atestado"].includes(p.tipo_dia||""))return 0;if(fimSemana(p.data))return trab(p);const limiteSaida=mins(j.saida)+j.tolSaida;return Math.max(0,mins(p.saida)-limiteSaida)};
 const devidaDia=(p:Ponto)=>{const j=jornadaDo(p);if(["feriado","folga","atestado"].includes(p.tipo_dia||""))return 0;const carga=j.carga||480;if(p.falta||p.tipo_dia==="falta")return carga;if(fimSemana(p.data))return 0;const faltaMin=Math.max(0,carga-trab(p));const tolerancia=Math.max(j.tolEntrada,j.tolSaida);return faltaMin<=tolerancia?0:faltaMin};
 const saldo=(p:Ponto)=>extraDia(p)-devidaDia(p);
 const lista=pontos.filter(p=>(!mesRef||p.data.slice(0,7)===mesRef)&&(!pessoa||p.colaboradora_id===pessoa));
 const calendario=useMemo(()=>diasDoMes(mesRef),[mesRef]);
 const calendarioPessoa=pessoa?calendario.map(d=>({ ...d, ponto: pontos.find(p=>p.colaboradora_id===pessoa&&p.data===d.data)||null })):[];
 const resumo=lista.reduce((r,p)=>{if(p.falta)r.faltas++;if(sabado(p.data)&&trab(p)>0)r.sabados++;r.extras+=extraDia(p);r.devidas+=devidaDia(p);return r},{extras:0,devidas:0,faltas:0,sabados:0});
 const horasTrabalhadas=lista.reduce((t,p)=>t+trab(p),0);
 const horasPrevistas=lista.filter(p=>!fimSemana(p.data)&&!["feriado","folga","atestado"].includes(p.tipo_dia||"")).reduce((t,p)=>{const j=jornadaDo(p);return t+(j.carga||480)},0);
 const extrasSabado=lista.filter(p=>sabado(p.data)).reduce((t,p)=>t+extraDia(p),0);
 const extrasDiasUteis=Math.max(0,resumo.extras-extrasSabado);
 const vh=numBR(valorHora), percSab=numBR(adicionalSabado);
 const valorExtraUtil=(extrasDiasUteis/60)*vh*1.5;
 const valorExtraSabado=(extrasSabado/60)*vh*(1+percSab/100);
 const valorExtrasTotal=valorExtraUtil+valorExtraSabado;
 const valorHorasDevedoras=(resumo.devidas/60)*vh;
 const saldoFinanceiro=valorExtrasTotal-valorHorasDevedoras;
 const fechamentoAtual=pessoa?fechamentos.find((x:any)=>x.colaboradora_id===pessoa&&x.competencia===mesRef):null;

 async function fecharCompetencia(){if(!pessoa){setMsg("Selecione uma colaboradora para fechar a competência.");return}const payload={colaboradora_id:pessoa,competencia:mesRef,horas_previstas_min:horasPrevistas,horas_trabalhadas_min:horasTrabalhadas,horas_extras_min:resumo.extras,horas_devedoras_min:resumo.devidas,faltas:resumo.faltas,valor_hora:vh,valor_extras:valorExtrasTotal,valor_devedoras:valorHorasDevedoras,saldo_financeiro:saldoFinanceiro,status:"FECHADO",fechado_em:new Date().toISOString()};const q=await sb.from("rh_fechamento_ponto").upsert(payload,{onConflict:"colaboradora_id,competencia"});if(q.error)setMsg(q.error.message);else{setMsg("Competência fechada com sucesso.");await carregar();setModalFechamento(false)}}
 async function reabrirCompetencia(){if(!fechamentoAtual)return;const q=await sb.from("rh_fechamento_ponto").update({status:"ABERTO",fechado_em:null}).eq("id",fechamentoAtual.id);if(q.error)setMsg(q.error.message);else{setMsg("Competência reaberta.");await carregar()}}
 function novo(dataAlvo?:string){const cid=pessoa||colaboradoras.find(c=>c.status!=="Desligada")?.id||"";const jid=vinculos.find(v=>v.colaboradora_id===cid)?.jornada_id||jornadaId||jornadas[0]?.id||"";const j=jornadas.find(x=>x.id===jid)||jornadas[0]||cfg;setEdit(null);setF({colaboradora_id:cid,jornada_id:jid,data:dataAlvo||hoje(),entrada:j.entrada,saida_almoco:j.saidaAlmoco,retorno_almoco:j.retornoAlmoco,saida:j.saida,falta:false,tipo_dia:"normal",observacao:""});setModal(true)}
 function editar(p:Ponto){setEdit(p.id);setF({colaboradora_id:p.colaboradora_id,jornada_id:p.jornada_id||"",data:p.data,entrada:String(p.entrada||cfg.entrada).slice(0,5),saida_almoco:String(p.saida_almoco||cfg.saidaAlmoco).slice(0,5),retorno_almoco:String(p.retorno_almoco||cfg.retornoAlmoco).slice(0,5),saida:String(p.saida||cfg.saida).slice(0,5),falta:p.falta,tipo_dia:p.tipo_dia||(p.falta?"falta":"normal"),observacao:p.observacao});setModal(true)}
 async function salvar(e:FormEvent){e.preventDefault();const semHorario=["falta","feriado","folga","atestado"].includes(f.tipo_dia);const p={...f,falta:f.tipo_dia==="falta",entrada:semHorario?null:f.entrada,saida_almoco:semHorario?null:f.saida_almoco,retorno_almoco:semHorario?null:f.retorno_almoco,saida:semHorario?null:f.saida};const q=edit?await sb.from("rh_ponto").update(p).eq("id",edit):await sb.from("rh_ponto").insert(p);if(q.error)setMsg(q.error.message);else{setModal(false);await carregar()}}
 async function excluir(id:string){if(!confirm("Excluir este registro de ponto?"))return;const q=await sb.from("rh_ponto").delete().eq("id",id);if(q.error)setMsg(q.error.message);else await carregar()}
 function gerenciarEquipe(j:Jornada){setJornadaEquipe(j);setSelecionados(vinculos.filter(v=>v.jornada_id===j.id).map(v=>v.colaboradora_id));setModalEquipe(true)}
 async function salvarEquipe(){if(!jornadaEquipe)return;const ids=selecionados;const atuais=vinculos.filter(v=>v.jornada_id===jornadaEquipe.id).map(v=>v.colaboradora_id);const remover=atuais.filter(id=>!ids.includes(id));if(remover.length){const q=await sb.from("rh_jornada_colaboradoras").delete().eq("jornada_id",jornadaEquipe.id).in("colaboradora_id",remover);if(q.error){setMsg(q.error.message);return}}for(const cid of ids){const q=await sb.from("rh_jornada_colaboradoras").upsert({colaboradora_id:cid,jornada_id:jornadaEquipe.id},{onConflict:"colaboradora_id"});if(q.error){setMsg(q.error.message);return}}setModalEquipe(false);await carregar()}
 async function salvarJornada(){const payload={nome:cfg.nome,entrada:cfg.entrada,saida_almoco:cfg.saidaAlmoco,retorno_almoco:cfg.retornoAlmoco,saida:cfg.saida,carga_diaria_min:cfg.carga,tolerancia_entrada_min:cfg.tolEntrada,tolerancia_saida_min:cfg.tolSaida};const q=jornadaId?await sb.from("rh_jornadas").update(payload).eq("id",jornadaId):await sb.from("rh_jornadas").insert(payload);if(q.error)setMsg(q.error.message);else{setModalJornada(false);setJornadaId("");await carregar()}}
 function novaJornada(){setJornadaId("");setCfg({nome:"",entrada:"08:30",saidaAlmoco:"12:00",retornoAlmoco:"13:30",saida:"18:00",carga:480,tolEntrada:5,tolSaida:5});setModalJornada(true)}
 function editarJornada(j:Jornada){setJornadaId(j.id);setCfg({nome:j.nome,entrada:j.entrada,saidaAlmoco:j.saidaAlmoco,retornoAlmoco:j.retornoAlmoco,saida:j.saida,carga:j.carga,tolEntrada:j.tolEntrada,tolSaida:j.tolSaida});setModalJornada(true)}
 async function excluirJornada(id:string){if(!confirm("Excluir esta jornada?"))return;const q=await sb.from("rh_jornadas").delete().eq("id",id);if(q.error)setMsg(q.error.message);else await carregar()}

 return <div className="bp">{msg&&<div className="bp-msg">{msg}</div>}
 <section className="bp-card bp-jornada-compacta"><div className="bp-jornadas-resumo"><div><b>JORNADAS / TURNOS</b><h2>{jornadas.length} horário(s) cadastrado(s)</h2><p>{vinculos.length} colaboradora(s) vinculada(s) aos turnos.</p></div><div className="bp-jornadas-resumo-acoes"><button type="button" className="sec" onClick={()=>setModalJornadas(true)}>Ver jornadas cadastradas</button><button type="button" onClick={novaJornada}>+ Nova jornada</button></div></div></section>
 <nav className="bp-subtabs"><button type="button" className={abaPonto==="registrar"?"on":""} onClick={()=>setAbaPonto("registrar")}>REGISTRAR PONTO</button><button type="button" className={abaPonto==="espelho"?"on":""} onClick={()=>setAbaPonto("espelho")}>ESPELHO / PONTOS CADASTRADOS</button></nav>
 {abaPonto==="registrar"&&<section className="bp-card bp-registro-home"><div><b>LANÇAMENTO MANUAL</b><h2>Registrar ponto</h2><p>Cadastre horários, faltas e observações de cada colaboradora.</p></div><button type="button" onClick={()=>novo()}>+ Novo ponto</button></section>}
 {abaPonto==="espelho"&&<>
 <div className="bp-resumo-faixa">
  <div><span>Horas extras</span><strong>{hm(resumo.extras)}</strong></div>
  <div><span>Horas devedoras</span><strong>{hm(resumo.devidas)}</strong></div>
  <div><span>Faltas</span><strong>{resumo.faltas}</strong></div>
  <div><span>Sábados</span><strong>{resumo.sabados}</strong></div>
 </div>
 <section className="bp-fechamento-faixa bp-fechamento-individual">
  <div className="bp-fechamento-faixa-info"><b>FECHAMENTO INDIVIDUAL</b><span>{pessoa?(colaboradoras.find(c=>c.id===pessoa)?.nome||"Colaboradora"):"Selecione uma colaboradora"} · {mesRef.split("-").reverse().join("/")}</span></div>
  {pessoa&&<><div className={`bp-resultado-mini ${resumo.devidas>0?"deve":valorExtrasTotal>0?"recebe":"zerado"}`}><span>{resumo.devidas>0?"COLABORADORA DEVE À EMPRESA":valorExtrasTotal>0?"EMPRESA DEVE À COLABORADORA":"SEM SALDO DE HORAS"}</span><strong>{resumo.devidas>0?hm(resumo.devidas):valorExtrasTotal>0?moeda(valorExtrasTotal):"0h00"}</strong>{valorExtrasTotal>0&&<small>{hm(resumo.extras)} de horas extras</small>}</div><button type="button" onClick={()=>setModalFechamento(true)}>{fechamentoAtual?.status==="FECHADO"?"Ver fechamento":"Fechar competência"}</button></>}
 </section>
 <section className="bp-card bp-espelho-grande"><div className="bp-filtros"><input type="month" value={mesRef} onChange={e=>setMesRef(e.target.value)}/><select value={pessoa} onChange={e=>setPessoa(e.target.value)}><option value="">Selecione uma colaboradora</option>{colaboradoras.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></div>
 {pessoa?<div className="bp-calendario-info"><div><b>ESPELHO MENSAL COMPLETO</b><span>{calendario.length} dias exibidos · dias sem lançamento ficam visíveis para conferência.</span></div><div className="bp-legenda"><span><i className="normal"></i>Normal</span><span><i className="devendo"></i>Devendo</span><span><i className="extra"></i>Extra</span><span><i className="fim"></i>Fim de semana</span><span><i className="feriado"></i>Feriado</span></div></div>:<div className="bp-calendario-aviso">Selecione uma colaboradora para visualizar todos os dias da competência.</div>}
 {pessoa&&<div className="bp-table bp-table-espelho"><table><thead><tr className="bp-head-grupo"><th rowSpan={2}>Data</th><th rowSpan={2}>Dia</th><th colSpan={4} className="bp-horarios-grupo">Horários</th><th rowSpan={2}>Trabalhado</th><th rowSpan={2}>Extra</th><th rowSpan={2}>Extra R$</th><th rowSpan={2}>Devedoras</th><th rowSpan={2}>Situação</th><th rowSpan={2}>Observação</th><th rowSpan={2}>Ação</th></tr><tr className="bp-head-sub"><th>Entrada</th><th>Almoço</th><th>Retorno</th><th>Saída</th></tr></thead><tbody>{calendarioPessoa.map(({data,dia,ponto})=>{const weekend=fimSemana(data);if(!ponto)return <tr key={data} className={weekend?"bp-dia-fimsemana":"bp-dia-pendente"}><td>{br(data)}</td><td>{dia}</td><td colSpan={7}>—</td><td>—</td><td><span className={`bp-status ${weekend?"folga":"pendente"}`}>{weekend?"Fim de semana":"Sem lançamento"}</span></td><td>—</td><td><button onClick={()=>novo(data)}>Registrar</button></td></tr>;const s=saldo(ponto),tipo=ponto.tipo_dia||(ponto.falta?"falta":"normal"),semHorario=["feriado","folga","atestado","falta"].includes(tipo);const label=tipo==="feriado"?"Feriado":tipo==="folga"?"Folga":tipo==="atestado"?"Atestado":tipo==="falta"?"Falta":weekend?"Hora extra":s<0?"Devendo":"Normal";return <tr key={data}><td>{br(data)}</td><td>{dia}</td><td>{semHorario?"—":String(ponto.entrada).slice(0,5)}</td><td>{semHorario?"—":String(ponto.saida_almoco).slice(0,5)}</td><td>{semHorario?"—":String(ponto.retorno_almoco).slice(0,5)}</td><td>{semHorario?"—":String(ponto.saida).slice(0,5)}</td><td>{semHorario?"—":hm(trab(ponto))}</td><td className="pos">{semHorario?"—":hm(extraDia(ponto))}</td><td className="pos">{semHorario?"—":moeda((extraDia(ponto)/60)*vh*(sabado(data)?(1+percSab/100):1.5))}</td><td className="neg">{tipo==="feriado"||tipo==="folga"||tipo==="atestado"?"0h00":hm(devidaDia(ponto))}</td><td><span className={`bp-status ${tipo==="feriado"?"feriado":tipo==="folga"?"folga":tipo==="atestado"?"atestado":tipo==="falta"?"falta":weekend?"extra":s<0?"devendo":"normal"}`}>{label}</span></td><td>{ponto.observacao||"—"}</td><td><button onClick={()=>editar(ponto)}>Editar</button></td></tr>})}</tbody></table></div>}
 </section>
 </>}
 {modalFechamento&&pessoa&&<div className="bp-bg"><div className="bp-modal bp-modal-fechamento">
  <header><div><b className="bp-modal-eyebrow">FECHAMENTO INDIVIDUAL</b><h2>{colaboradoras.find(c=>c.id===pessoa)?.nome}</h2><small>Competência {mesRef.split("-").reverse().join("/")} {fechamentoAtual?.status==="FECHADO"?"· FECHADA":""}</small></div><button type="button" onClick={()=>setModalFechamento(false)}>×</button></header>
  <div className="bp-fechamento-modal-body">
   <div className="bp-modal-metricas"><article><span>Horas previstas</span><strong>{hm(horasPrevistas)}</strong></article><article><span>Horas trabalhadas</span><strong>{hm(horasTrabalhadas)}</strong></article><article><span>Horas extras</span><strong>{hm(resumo.extras)}</strong><small>{moeda(valorExtrasTotal)}</small></article><article><span>Horas devedoras</span><strong>{hm(resumo.devidas)}</strong><small>Tempo devido à empresa</small></article><article><span>Faltas</span><strong>{resumo.faltas}</strong></article><article><span>Valor da hora</span><strong>{moeda(vh)}</strong></article></div>
   <div className="bp-origem-extras"><div className="bp-origem-extras-head"><b>DE ONDE VIERAM AS HORAS EXTRAS</b><span>{hm(resumo.extras)} no total</span></div>{lista.filter(p=>extraDia(p)>0).length?lista.filter(p=>extraDia(p)>0).map(p=>{const j=jornadaDo(p);return <div className="bp-extra-dia" key={p.id}><span><b>{br(p.data)}</b> · {j.nome}</span><span>Trabalhado {hm(trab(p))}</span><strong>+ {hm(extraDia(p))}</strong></div>}):<div className="bp-extra-vazio">Nenhum dia gerou hora extra nesta competência.</div>}</div>
   <div className={`bp-resultado-final ${resumo.devidas>0?"deve":valorExtrasTotal>0?"recebe":"zerado"}`}><div><span>RESULTADO DO FECHAMENTO</span><strong>{resumo.devidas>0?"COLABORADORA DEVE À EMPRESA":valorExtrasTotal>0?"EMPRESA DEVE À COLABORADORA":"SEM SALDO DE HORAS"}</strong>{resumo.devidas>0&&valorExtrasTotal>0&&<small>Também existem {hm(resumo.extras)} de horas extras, no valor de {moeda(valorExtrasTotal)}.</small>}</div><b>{resumo.devidas>0?hm(resumo.devidas):valorExtrasTotal>0?moeda(valorExtrasTotal):"0h00"}</b></div>
   <p className="bp-aviso-fechamento">{resumo.devidas>0?"Horas devedoras são demonstradas somente em tempo. Não há conversão para valor a pagar pela colaboradora.":"Valores em reais são exibidos somente para horas extras a pagar pela empresa."}</p>
  </div>
  <footer>{fechamentoAtual?.status==="FECHADO"?<><button type="button" onClick={()=>setModalFechamento(false)}>Fechar</button><button type="button" onClick={()=>void reabrirCompetencia()}>Reabrir competência</button></>:<><button type="button" onClick={()=>setModalFechamento(false)}>Cancelar</button><button type="button" onClick={()=>void fecharCompetencia()}>Confirmar fechamento</button></>}</footer>
 </div></div>}
 {modalJornadas&&<div className="bp-bg"><div className="bp-modal bp-modal-jornadas"><header><div><h2>Jornadas cadastradas</h2><small>Escolha um horário para gerenciar equipe, editar ou excluir.</small></div><button type="button" onClick={()=>setModalJornadas(false)}>×</button></header><div className="bp-jornadas-modal-lista">{jornadas.length?jornadas.map(j=><article key={j.id}><div><strong>{j.nome}</strong><span>{j.entrada} às {j.saida} · almoço {j.saidaAlmoco}–{j.retornoAlmoco}</span><small>Tolerância: {j.tolEntrada} min entrada / {j.tolSaida} min saída · {vinculos.filter(v=>v.jornada_id===j.id).length} colaboradora(s)</small></div><div className="acoes"><button type="button" onClick={()=>{setModalJornadas(false);gerenciarEquipe(j)}}>Gerenciar equipe</button><button type="button" onClick={()=>{setModalJornadas(false);editarJornada(j)}}>Editar</button><button type="button" className="del" onClick={()=>void excluirJornada(j.id)}>Excluir</button></div></article>):<p className="bp-vazio">Nenhuma jornada cadastrada.</p>}</div><footer><button type="button" onClick={()=>setModalJornadas(false)}>Fechar</button><button type="button" onClick={()=>{setModalJornadas(false);novaJornada()}}>+ Nova jornada</button></footer></div></div>}
 {modalEquipe&&jornadaEquipe&&<div className="bp-bg"><div className="bp-modal"><header><div><h2>Equipe da jornada</h2><small>{jornadaEquipe.nome} · {jornadaEquipe.entrada}–{jornadaEquipe.saida}</small></div><button type="button" onClick={()=>setModalEquipe(false)}>×</button></header><div className="bp-equipe-lista">{colaboradoras.filter(c=>c.status!=="Desligada").map(c=>{const outro=vinculos.find(v=>v.colaboradora_id===c.id&&v.jornada_id!==jornadaEquipe.id);return <label key={c.id} className={outro?"ocupado":""}><input type="checkbox" checked={selecionados.includes(c.id)} onChange={e=>setSelecionados(a=>e.target.checked?[...a,c.id]:a.filter(id=>id!==c.id))}/><span><b>{c.nome}</b>{outro&&<small>Atualmente em: {jornadas.find(j=>j.id===outro.jornada_id)?.nome||"outra jornada"} — ao salvar será transferida.</small>}</span></label>})}</div><footer><button type="button" onClick={()=>setModalEquipe(false)}>Cancelar</button><button type="button" onClick={()=>void salvarEquipe()}>Salvar equipe</button></footer></div></div>}
 {modalJornada&&<div className="bp-bg"><div className="bp-modal"><header><h2>Configurar jornada</h2><button type="button" onClick={()=>setModalJornada(false)}>×</button></header><div className="bp-form"><label className="wide">Nome da jornada<input value={cfg.nome} onChange={e=>setCfg({...cfg,nome:e.target.value})} placeholder="Ex.: Jornada 08:00"/></label>{[["Entrada","entrada"],["Saída almoço","saidaAlmoco"],["Retorno almoço","retornoAlmoco"],["Saída","saida"]].map(([rotulo,chave])=><label key={chave}>{rotulo}<input type="time" value={(cfg as any)[chave]} onChange={e=>setCfg({...cfg,[chave]:e.target.value})}/></label>)}<label>Tolerância entrada (min)<input type="number" min="0" value={cfg.tolEntrada} onChange={e=>setCfg({...cfg,tolEntrada:Number(e.target.value||0)})}/></label><label>Tolerância saída (min)<input type="number" min="0" value={cfg.tolSaida} onChange={e=>setCfg({...cfg,tolSaida:Number(e.target.value||0)})}/></label></div><footer><button type="button" onClick={()=>setModalJornada(false)}>Cancelar</button><button type="button" onClick={()=>void salvarJornada()}>Salvar jornada</button></footer></div></div>}
 {modal&&<div className="bp-bg"><form className="bp-modal" onSubmit={salvar}><header><h2>{edit?"Editar":"Novo"} ponto</h2><button type="button" onClick={()=>setModal(false)}>×</button></header><div className="bp-form"><label>Colaboradora<select required value={f.colaboradora_id} onChange={e=>{const cid=e.target.value,jid=vinculos.find(v=>v.colaboradora_id===cid)?.jornada_id||"",j=jornadas.find(x=>x.id===jid);setF({...f,colaboradora_id:cid,jornada_id:jid,...(j?{entrada:j.entrada,saida_almoco:j.saidaAlmoco,retorno_almoco:j.retornoAlmoco,saida:j.saida}:{})})}}><option value="">Selecione</option>{colaboradoras.filter(c=>c.status!=="Desligada").map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Jornada / turno<select required value={f.jornada_id} disabled><option value="">Selecione</option>{jornadas.map(j=><option key={j.id} value={j.id}>{j.nome} · {j.entrada}–{j.saida}</option>)}</select></label><label>Data<input type="date" required value={f.data} onChange={e=>setF({...f,data:e.target.value})}/></label><label>Tipo do dia<select value={f.tipo_dia} onChange={e=>setF({...f,tipo_dia:e.target.value,falta:e.target.value==="falta"})}><option value="normal">Dia normal</option><option value="falta">Falta</option><option value="feriado">Feriado — sem expediente</option><option value="folga">Folga</option><option value="atestado">Atestado / afastamento</option></select></label>{f.tipo_dia==="normal"&&<>{[["Entrada","entrada"],["Saída almoço","saida_almoco"],["Retorno almoço","retorno_almoco"],["Saída","saida"]].map(([rotulo,chave])=><label key={chave}>{rotulo}<input type="time" value={(f as any)[chave]} onChange={e=>setF({...f,[chave]:e.target.value})}/></label>)}</>}<label className="wide">Observação<textarea value={f.observacao} onChange={e=>setF({...f,observacao:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button>Salvar ponto</button></footer></form></div>}
 </div>
}