"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type StatusOcorrencia="Pendente de reposição"|"Em reposição"|"Finalizado";
type TipoOcorrencia=string;
type Ocorrencia={id:string;data:string;titulo:string;tipo:TipoOcorrencia;equipe:string;descricao:string;precisa_reposicao:boolean;data_reposicao:string|null;observacao_reposicao:string;status:StatusOcorrencia;criado_em:string};
const hoje=()=>new Date().toISOString().slice(0,10),mesAtual=()=>hoje().slice(0,7),br=(v:string|null)=>v?v.slice(0,10).split("-").reverse().join("/"):"—";
const vazio={data:hoje(),titulo:"",tipo:"Energia" as TipoOcorrencia,equipe:"Toda a empresa",descricao:"",precisa_reposicao:false,data_reposicao:"",observacao_reposicao:"",status:"Finalizado" as StatusOcorrencia};

export default function OcorrenciasEmpresaRH(){
 const sb=useMemo(()=>createClient(),[]),[lista,setLista]=useState<Ocorrencia[]>([]),[mes,setMes]=useState(mesAtual()),[status,setStatus]=useState(""),[equipe,setEquipe]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<string|null>(null),[form,setForm]=useState(vazio),[msg,setMsg]=useState(""),[salvando,setSalvando]=useState(false),[novoTipo,setNovoTipo]=useState("");
 async function carregar(){const q=await sb.from("rh_ocorrencias_empresa").select("*").order("data",{ascending:false});if(q.error)setMsg(q.error.message);else setLista((q.data||[]) as Ocorrencia[])}
 useEffect(()=>{void carregar()},[]);
 const equipes=useMemo(()=>Array.from(new Set(lista.map(x=>x.equipe).filter(Boolean))).sort(),[lista]);
 const filtradas=useMemo(()=>lista.filter(x=>(!mes||x.data.slice(0,7)===mes)&&(!status||x.status===status)&&(!equipe||x.equipe===equipe)),[lista,mes,status,equipe]);
 function nova(){setEdit(null);setForm(vazio);setNovoTipo("");setModal(true);setMsg("")}
 function editar(x:Ocorrencia){setNovoTipo("");setEdit(x.id);setForm({data:x.data.slice(0,10),titulo:x.titulo,tipo:x.tipo,equipe:x.equipe,descricao:x.descricao||"",precisa_reposicao:!!x.precisa_reposicao,data_reposicao:x.data_reposicao?x.data_reposicao.slice(0,10):"",observacao_reposicao:x.observacao_reposicao||"",status:x.status});setModal(true)}
 async function salvar(e:FormEvent){e.preventDefault();if(!form.titulo.trim()){setMsg("Informe o título da ocorrência.");return}const tipoFinal=form.tipo==="__novo__"?novoTipo.trim():form.tipo;if(!tipoFinal){setMsg("Informe o tipo da ocorrência.");return}setSalvando(true);const payload={data:form.data,titulo:form.titulo.trim(),tipo:tipoFinal,equipe:form.equipe.trim()||"Toda a empresa",descricao:form.descricao.trim(),precisa_reposicao:form.precisa_reposicao,data_reposicao:form.precisa_reposicao&&form.data_reposicao?form.data_reposicao:null,observacao_reposicao:form.precisa_reposicao?form.observacao_reposicao.trim():"",status:form.precisa_reposicao?form.status:"Finalizado",atualizado_em:new Date().toISOString()};const q=edit?await sb.from("rh_ocorrencias_empresa").update(payload).eq("id",edit):await sb.from("rh_ocorrencias_empresa").insert(payload);setSalvando(false);if(q.error)setMsg(q.error.message);else{setModal(false);await carregar()}}
 async function excluir(id:string){if(!confirm("Excluir esta ocorrência?"))return;const q=await sb.from("rh_ocorrencias_empresa").delete().eq("id",id);if(q.error)setMsg(q.error.message);else await carregar()}
 return <section className="hrm-panel"><div className="hrm-section-heading"><div><span className="hrm-eyebrow">HISTÓRICO DA EMPRESA</span><h2>Ocorrências</h2><p>Registre imprevistos, equipes afetadas e reposições.</p></div><button type="button" className="hrm-button hrm-primary" onClick={nova}>+ Nova ocorrência</button></div>
 {msg&&<div className="hrm-notice">{msg}</div>}
 <div className="hrm-history-filters"><input type="month" value={mes} onChange={e=>setMes(e.target.value)}/><select value={equipe} onChange={e=>setEquipe(e.target.value)}><option value="">Todas as equipes</option>{equipes.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option>Pendente de reposição</option><option>Em reposição</option><option>Finalizado</option></select></div>
 <div className="hrm-occurrence-list">{!filtradas.length?<div className="hrm-empty">Nenhuma ocorrência encontrada.</div>:filtradas.map(x=><article key={x.id} className="hrm-occurrence-card"><div className="hrm-occurrence-date"><strong>{br(x.data)}</strong><span>{x.tipo}</span></div><div className="hrm-occurrence-main"><div className="hrm-occurrence-title"><h3>{x.titulo}</h3><span className="hrm-occurrence-status">{x.status}</span></div><p><b>Equipe:</b> {x.equipe}</p>{x.descricao&&<p>{x.descricao}</p>}{x.precisa_reposicao&&<div className="hrm-reposicao-box"><b>Reposição</b><span>{x.data_reposicao?`Data: ${br(x.data_reposicao)}`:"Data ainda não definida"}</span>{x.observacao_reposicao&&<p>{x.observacao_reposicao}</p>}</div>}</div><div className="hrm-occurrence-actions"><button type="button" className="hrm-link" onClick={()=>editar(x)}>Editar</button><button type="button" className="hrm-text-danger" onClick={()=>void excluir(x.id)}>Excluir</button></div></article>)}</div>
 {modal&&<div className="hrm-occurrence-bg"><form className="hrm-occurrence-modal" onSubmit={salvar}><header><div><span className="hrm-eyebrow">OCORRÊNCIA DA EMPRESA</span><h2>{edit?"Editar ocorrência":"Nova ocorrência"}</h2></div><button type="button" onClick={()=>setModal(false)}>×</button></header><div className="hrm-occurrence-form"><label>Data<input type="date" required value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></label><label>Tipo<select value={form.tipo} onChange={e=>{const v=e.target.value;setForm({...form,tipo:v});if(v!=="__novo__")setNovoTipo("")}}><option>Energia</option><option>Internet</option><option>Sistema</option><option>Banco</option><option>Expediente</option><option>Outro</option><option value="__novo__">+ Criar novo tipo</option></select>{form.tipo==="__novo__"&&<input className="hrm-occurrence-new-type" autoFocus value={novoTipo} onChange={e=>setNovoTipo(e.target.value)} placeholder="Digite o novo tipo. Ex.: Manutenção"/>}</label><label className="wide">Título<input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Ex.: Empresa ficou sem energia"/></label><label className="wide">Equipe afetada<input value={form.equipe} onChange={e=>setForm({...form,equipe:e.target.value})} placeholder="Ex.: CLT ou Toda a empresa"/></label><label className="wide">Descrição<textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label className="hrm-occurrence-check wide"><input type="checkbox" checked={form.precisa_reposicao} onChange={e=>setForm({...form,precisa_reposicao:e.target.checked,status:e.target.checked?"Pendente de reposição":"Finalizado"})}/><span>Precisa de reposição de horas</span></label>{form.precisa_reposicao&&<><label>Data da reposição<input type="date" value={form.data_reposicao} onChange={e=>setForm({...form,data_reposicao:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as StatusOcorrencia})}><option>Pendente de reposição</option><option>Em reposição</option><option>Finalizado</option></select></label><label className="wide">Observação da reposição<textarea value={form.observacao_reposicao} onChange={e=>setForm({...form,observacao_reposicao:e.target.value})} placeholder="Ex.: Meninas do CLT estão repondo em 26/09 as horas do dia 21/09."/></label></>}</div><footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button disabled={salvando}>{salvando?"Salvando…":"Salvar ocorrência"}</button></footer></form></div>}</section>
}