"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Status="Pendente de reposição"|"Em reposição"|"Finalizado";
type Pessoa={id:string;nome:string;equipe?:string};
type Oc={id:string;data:string;titulo:string;tipo:string;equipe:string;descricao:string;precisa_reposicao:boolean;data_reposicao:string|null;observacao_reposicao:string;status:Status;pessoas_afetadas?:string[]};
const hoje=()=>new Date().toISOString().slice(0,10),mesAtual=()=>hoje().slice(0,7),br=(v:string|null)=>v?v.slice(0,10).split("-").reverse().join("/"):"—";
const vazio={data:hoje(),titulo:"",tipo:"Energia",equipe:"Toda a empresa",descricao:"",precisa_reposicao:false,data_reposicao:"",observacao_reposicao:"",status:"Finalizado" as Status,pessoas_afetadas:[] as string[]};
export default function OcorrenciasEmpresaRH(){
 const sb=useMemo(()=>createClient(),[]);const[lista,setLista]=useState<Oc[]>([]),[pessoas,setPessoas]=useState<Pessoa[]>([]),[mes,setMes]=useState(mesAtual()),[status,setStatus]=useState(""),[equipe,setEquipe]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState<string|null>(null),[form,setForm]=useState(vazio),[msg,setMsg]=useState(""),[novoTipo,setNovoTipo]=useState(""),[novaEquipe,setNovaEquipe]=useState("");
 async function carregar(){const[a,b]=await Promise.all([sb.from("rh_ocorrencias_empresa").select("*").order("data",{ascending:false}),sb.from("rh_colaboradoras").select("id,nome,equipe").order("nome")]);if(a.error)setMsg(a.error.message);else setLista((a.data||[]) as Oc[]);if(!b.error)setPessoas((b.data||[]) as Pessoa[])} useEffect(()=>{void carregar()},[]);
 const equipes=useMemo(()=>Array.from(new Set(["Equipe CLT","Equipe Compra de Dívida",...pessoas.map(x=>x.equipe||""),...lista.map(x=>x.equipe||"")].filter(Boolean))).sort(),[pessoas,lista]);
 const filtradas=lista.filter(x=>(!mes||x.data.slice(0,7)===mes)&&(!status||x.status===status)&&(!equipe||x.equipe===equipe));
 const disponiveis=form.equipe==="Toda a empresa"?pessoas:pessoas.filter(x=>(x.equipe||"").toLowerCase().includes(form.equipe.toLowerCase().replace("equipe ","")));
 function nova(){setEdit(null);setForm({...vazio,pessoas_afetadas:[]});setNovoTipo("");setNovaEquipe("");setModal(true)}function editar(x:Oc){setEdit(x.id);setForm({...vazio,...x,data:x.data.slice(0,10),data_reposicao:x.data_reposicao?.slice(0,10)||"",pessoas_afetadas:x.pessoas_afetadas||[]});setModal(true)}function toggle(id:string){setForm(f=>({...f,pessoas_afetadas:f.pessoas_afetadas.includes(id)?f.pessoas_afetadas.filter(x=>x!==id):[...f.pessoas_afetadas,id]}))}
 async function salvar(e:FormEvent){e.preventDefault();const tipo=form.tipo==="__novo__"?novoTipo.trim():form.tipo,eq=form.equipe==="__nova__"?novaEquipe.trim():form.equipe;if(!form.titulo.trim()||!tipo||!eq){setMsg("Preencha título, tipo e equipe.");return}const payload={data:form.data,titulo:form.titulo.trim(),tipo,equipe:eq,descricao:form.descricao.trim(),precisa_reposicao:form.precisa_reposicao,data_reposicao:form.precisa_reposicao&&form.data_reposicao?form.data_reposicao:null,observacao_reposicao:form.precisa_reposicao?form.observacao_reposicao.trim():"",status:form.precisa_reposicao?form.status:"Finalizado",pessoas_afetadas:form.pessoas_afetadas,atualizado_em:new Date().toISOString()};const q=edit?await sb.from("rh_ocorrencias_empresa").update(payload).eq("id",edit):await sb.from("rh_ocorrencias_empresa").insert(payload);if(q.error)setMsg(q.error.message);else{setModal(false);await carregar()}}
 async function excluir(id:string){if(!confirm("Excluir esta ocorrência?"))return;const q=await sb.from("rh_ocorrencias_empresa").delete().eq("id",id);if(q.error)setMsg(q.error.message);else await carregar()}
 const nomes=(ids:string[])=>(ids||[]).map(id=>pessoas.find(p=>p.id===id)?.nome).filter(Boolean).join(", ");
 return <section className="hrm-panel"><div className="hrm-section-heading"><div><span className="hrm-eyebrow">HISTÓRICO DA EMPRESA</span><h2>Ocorrências</h2><p>Registre imprevistos, equipes afetadas e reposições.</p></div><button className="hrm-button hrm-primary" onClick={nova}>+ Nova ocorrência</button></div>{msg&&<div className="hrm-notice">{msg}</div>}
 <div className="hrm-history-filters"><input type="month" value={mes} onChange={e=>setMes(e.target.value)}/><select value={equipe} onChange={e=>setEquipe(e.target.value)}><option value="">Todas as equipes</option>{equipes.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option>Pendente de reposição</option><option>Em reposição</option><option>Finalizado</option></select></div>
 <div className="hrm-occurrence-list">{!filtradas.length?<div className="hrm-empty">Nenhuma ocorrência encontrada.</div>:filtradas.map(x=><article className="hrm-occurrence-card" key={x.id}><div className="hrm-occurrence-date"><strong>{br(x.data)}</strong><span>{x.tipo}</span></div><div className="hrm-occurrence-main"><div className="hrm-occurrence-title"><h3>{x.titulo}</h3><span className={`hrm-occurrence-status ${x.status==="Finalizado"?"status-finalizado":"status-pendente"}`}>{x.status==="Finalizado"?"✓ CONCLUÍDO":x.status}</span></div><p><b>Equipe:</b> {x.equipe}</p>{!!x.pessoas_afetadas?.length&&<p><b>Pessoas afetadas:</b> {nomes(x.pessoas_afetadas)}</p>}{x.descricao&&<p>{x.descricao}</p>}{x.precisa_reposicao&&<div className="hrm-reposicao-box"><b>Reposição</b><span>{x.data_reposicao?`Data: ${br(x.data_reposicao)}`:"Data ainda não definida"}</span>{x.observacao_reposicao&&<p>{x.observacao_reposicao}</p>}</div>}</div><div className="hrm-occurrence-actions"><button className="hrm-action-edit" onClick={()=>editar(x)}>Editar</button><button className="hrm-action-delete" onClick={()=>void excluir(x.id)}>Excluir</button></div></article>)}</div>
 {modal&&<div className="hrm-occurrence-bg"><form className="hrm-occurrence-modal" onSubmit={salvar}><header><div><span className="hrm-eyebrow">OCORRÊNCIA DA EMPRESA</span><h2>{edit?"Editar ocorrência":"Nova ocorrência"}</h2></div><button type="button" onClick={()=>setModal(false)}>×</button></header><div className="hrm-occurrence-form"><label>Data<input type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>Energia</option><option>Internet</option><option>Sistema</option><option>Banco</option><option>Expediente</option><option>Outro</option><option value="__novo__">+ Criar novo tipo</option></select>{form.tipo==="__novo__"&&<input value={novoTipo} onChange={e=>setNovoTipo(e.target.value)} placeholder="Digite o novo tipo"/>}</label><label className="wide">Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></label><label className="wide">Equipe afetada<select value={form.equipe} onChange={e=>setForm({...form,equipe:e.target.value,pessoas_afetadas:[]})}><option>Toda a empresa</option><option>Equipe CLT</option><option>Equipe Compra de Dívida</option>{equipes.filter(x=>!["Equipe CLT","Equipe Compra de Dívida"].includes(x)).map(x=><option key={x}>{x}</option>)}<option value="__nova__">+ Criar nova equipe</option></select>{form.equipe==="__nova__"&&<input value={novaEquipe} onChange={e=>setNovaEquipe(e.target.value)} placeholder="Nome da nova equipe"/>}</label><div className="wide hrm-affected-box"><b>Pessoas afetadas</b><div className="hrm-affected-list">{disponiveis.map(p=><label key={p.id} className="hrm-person-check"><input type="checkbox" checked={form.pessoas_afetadas.includes(p.id)} onChange={()=>toggle(p.id)}/><span>{p.nome}</span></label>)}</div></div><label className="wide">Descrição<textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label className="hrm-occurrence-check wide"><input type="checkbox" checked={form.precisa_reposicao} onChange={e=>setForm({...form,precisa_reposicao:e.target.checked,status:e.target.checked?"Pendente de reposição":"Finalizado"})}/><span>Precisa de reposição de horas</span></label>{form.precisa_reposicao&&<><label>Data da reposição<input type="date" value={form.data_reposicao} onChange={e=>setForm({...form,data_reposicao:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option>Pendente de reposição</option><option>Em reposição</option><option>Finalizado</option></select></label><label className="wide">Observação da reposição<textarea value={form.observacao_reposicao} onChange={e=>setForm({...form,observacao_reposicao:e.target.value})}/></label></>}</div><footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button>Salvar ocorrência</button></footer></form></div>}</section>
}