export const seedData = {
  "version": "planilha-14-v1",
  "sourceFile": "PAGAMENTO DE COMISSÃO COMPRA - BLU (14).xlsx",
  "proposals": [
    {
      "id": "planilha-compra-4",
      "numero": "20260527243682",
      "cliente": "DANIELA PAULA DE ARRUDA ALVES SIQUEIRA",
      "cpf": "152.983.318.31",
      "banco": "NEO",
      "tabela": "NEO FLEX 1 - 82%",
      "produto": "Compra de Dívida",
      "valorOperacao": 8933.41,
      "valorLiquido": 7325.3962,
      "comissaoPrevista": 2188.68545,
      "valorRecebido": 2188.69,
      "percentualComissao": 0.245,
      "diferenca": 0.00455,
      "consultora": "RAISSA",
      "dataDigitacao": "2026-05-27",
      "dataPagamento": "2026-06-09",
      "dataRecebimento": "2026-06-16",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-05-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-5",
      "numero": "20260611247963",
      "cliente": "MATHEUS PEREIRA DE SOUZA",
      "cpf": "379.097.668-74",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 19562.87,
      "valorLiquido": 19562.87,
      "comissaoPrevista": 5575.41795,
      "valorRecebido": 5477.6,
      "percentualComissao": 0.285,
      "diferenca": -97.81795,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-11",
      "dataPagamento": "2026-06-19",
      "dataRecebimento": "2026-06-23",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU MENOS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-6",
      "numero": "20260616248910",
      "cliente": "JULIANA GOMES MIGUEL",
      "cpf": "364.906.178-38",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 23996.96,
      "valorLiquido": 8878.8752,
      "comissaoPrevista": 2519.6808,
      "valorRecebido": 2519.68,
      "percentualComissao": 0.105,
      "diferenca": -0.0007999999998,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-16",
      "dataPagamento": "2026-06-24",
      "dataRecebimento": "2026-06-30",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-7",
      "numero": "20260610247456",
      "cliente": "MARIA DA CONCEIÇÃO DOS SANTOS SILVA",
      "cpf": "093.625.214-66",
      "banco": "NEO",
      "tabela": "NEO FLEX 1 - 82%",
      "produto": "Compra de Dívida",
      "valorOperacao": 18584.41,
      "valorLiquido": 15239.2162,
      "comissaoPrevista": 4553.18045,
      "valorRecebido": 4553.18,
      "percentualComissao": 0.245,
      "diferenca": -0.0004499999995,
      "consultora": "RAISSA",
      "dataDigitacao": "2026-06-10",
      "dataPagamento": "2026-06-24",
      "dataRecebimento": "2026-06-30",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-8",
      "numero": "20260619249907",
      "cliente": "THAIS MAIA DA SILVA",
      "cpf": "405.776.018-06",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 12941.87,
      "valorLiquido": 12941.87,
      "comissaoPrevista": 3688.43295,
      "valorRecebido": 3688.43,
      "percentualComissao": 0.285,
      "diferenca": -0.00295,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-06-19",
      "dataPagamento": "2026-06-25",
      "dataRecebimento": "2026-06-30",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-9",
      "numero": "20260623250845",
      "cliente": "VERONICA DULCINEIA BACHA MOTTA",
      "cpf": "141.363.158-48",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 18352.32,
      "valorLiquido": 18352.32,
      "comissaoPrevista": 5230.4112,
      "valorRecebido": 5092.77,
      "percentualComissao": 0.285,
      "diferenca": -137.6412,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-23",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "2026-07-08",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU MENOS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-10",
      "numero": "20260622250375",
      "cliente": "RAMON DOS SANTOS DE MORAIS",
      "cpf": "424.040.908-01",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 18272.46,
      "valorLiquido": 18272.46,
      "comissaoPrevista": 5207.6511,
      "valorRecebido": 5481.74,
      "percentualComissao": 0.285,
      "diferenca": 274.0889,
      "consultora": "VINICIUS",
      "dataDigitacao": "2026-06-22",
      "dataPagamento": "2026-07-13",
      "dataRecebimento": "2026-07-13",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-11",
      "numero": "20260623250804",
      "cliente": "CARLOS ROBERTO DA SILVA",
      "cpf": "059.463.698-14",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 13529.43,
      "valorLiquido": 13529.43,
      "comissaoPrevista": 3855.88755,
      "valorRecebido": 3754.42,
      "percentualComissao": 0.285,
      "diferenca": -101.46755,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-06-23",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "2026-07-08",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU MENOS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-12",
      "numero": "20260623250577",
      "cliente": "RICARDO CLEMENTE VERISSIMO DA SILVA",
      "cpf": "222.020.968-76",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 22393.58,
      "valorLiquido": 8285.6246,
      "comissaoPrevista": 2351.3259,
      "valorRecebido": 2485.69,
      "percentualComissao": 0.105,
      "diferenca": 134.3641,
      "consultora": "RAISSA",
      "dataDigitacao": "2026-06-23",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "2026-07-09",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-13",
      "numero": "20260624251113",
      "cliente": "AGUINALDO FERREIRA DA SILVA",
      "cpf": "131.148.568-61",
      "banco": "NEO",
      "tabela": "NEO FLEX 2 - 67%",
      "produto": "Compra de Dívida",
      "valorOperacao": 19562.11,
      "valorLiquido": 13106.6137,
      "comissaoPrevista": 4010.23255,
      "valorRecebido": 0.0,
      "percentualComissao": 0.205,
      "diferenca": 0.0,
      "consultora": "RAYANE",
      "dataDigitacao": "2026-06-24",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-14",
      "numero": "20260624251096",
      "cliente": "MARCIA ROCHA",
      "cpf": "127.567.358-92",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 24130.8,
      "valorLiquido": 24130.8,
      "comissaoPrevista": 6877.278,
      "valorRecebido": 6696.3,
      "percentualComissao": 0.285,
      "diferenca": -180.978,
      "consultora": "GABRIELA",
      "dataDigitacao": "2026-06-24",
      "dataPagamento": "2026-07-13",
      "dataRecebimento": "2026-07-13",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU MENOS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-15",
      "numero": "20260624251131",
      "cliente": "MARIO MANOEL DE MELO",
      "cpf": "267.114.228-56",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 28697.11,
      "valorLiquido": 10617.9307,
      "comissaoPrevista": 3013.19655,
      "valorRecebido": 3185.38,
      "percentualComissao": 0.105,
      "diferenca": 172.18345,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-24",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "2026-07-09",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-16",
      "numero": "20260625251201",
      "cliente": "LUIZ ALBERTO TAVARES",
      "cpf": "306.906.948-73",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 21190.96,
      "valorLiquido": 7840.6552,
      "comissaoPrevista": 2225.0508,
      "valorRecebido": 2352.2,
      "percentualComissao": 0.105,
      "diferenca": 127.1492,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-06-25",
      "dataPagamento": "2026-06-30",
      "dataRecebimento": "2026-07-09",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-17",
      "numero": "20260624250965",
      "cliente": "ANDREA LAVORATO DOS SANTOS",
      "cpf": "153.658.528-93",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 9276.03,
      "valorLiquido": 3432.1311,
      "comissaoPrevista": 973.98315,
      "valorRecebido": 1029.64,
      "percentualComissao": 0.105,
      "diferenca": 55.65685,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-24",
      "dataPagamento": "2026-07-02",
      "dataRecebimento": "2026-07-08",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-18",
      "numero": "20260625251324",
      "cliente": "GILBERTO ALVES",
      "cpf": "196.530.968-26",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 31070.23,
      "valorLiquido": 11495.9851,
      "comissaoPrevista": 3262.37415,
      "valorRecebido": 3448.8,
      "percentualComissao": 0.105,
      "diferenca": 186.42585,
      "consultora": "VALDENIA",
      "dataDigitacao": "2026-06-25",
      "dataPagamento": "2026-07-03",
      "dataRecebimento": "2026-07-08",
      "status": "Pago",
      "statusFinanceiro": "RECEBEU O VALOR A MAIS",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-19",
      "numero": "20260625251223",
      "cliente": "VICTOR SIQUEIRA DE MENEZES SANTOS",
      "cpf": "402.980.848-48",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 17820.92,
      "valorLiquido": 17820.92,
      "comissaoPrevista": 5078.9622,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "RAISSA",
      "dataDigitacao": "2026-06-25",
      "dataPagamento": "2026-07-06",
      "dataRecebimento": "",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-20",
      "numero": "20260626251765",
      "cliente": "MARIA HELENA DE SOUZA",
      "cpf": "110.780.638-00",
      "banco": "NEO",
      "tabela": "NEO FLEX 1 - 82%",
      "produto": "Compra de Dívida",
      "valorOperacao": 10823.45,
      "valorLiquido": 8875.229,
      "comissaoPrevista": 2651.74525,
      "valorRecebido": 0.0,
      "percentualComissao": 0.245,
      "diferenca": 0.0,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-26",
      "dataPagamento": "2026-07-09",
      "dataRecebimento": "",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-21",
      "numero": "20260625251441",
      "cliente": "ANDRE LUIS DE GOES",
      "cpf": "068.059.558-90",
      "banco": "NEO",
      "tabela": "NEO FLEX 2 - 67%",
      "produto": "Compra de Dívida",
      "valorOperacao": 24822.11,
      "valorLiquido": 16630.8137,
      "comissaoPrevista": 5088.53255,
      "valorRecebido": 0.0,
      "percentualComissao": 0.205,
      "diferenca": 0.0,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-25",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-06-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-22",
      "numero": "20260630252218",
      "cliente": "CESAR MANOEL DOS REIS",
      "cpf": "078.735.988-29",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 33511.12,
      "valorLiquido": 33511.12,
      "comissaoPrevista": 9550.6692,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-06-30",
      "dataPagamento": "2026-07-07",
      "dataRecebimento": "",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-23",
      "numero": "20260626251873",
      "cliente": "MARISA APARECIDA SANTANA LOPES",
      "cpf": "049.633.878-16",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 9127.07,
      "valorLiquido": 9127.07,
      "comissaoPrevista": 2601.21495,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "ERICA",
      "dataDigitacao": "2026-06-26",
      "dataPagamento": "2026-07-08",
      "dataRecebimento": "",
      "status": "Pago",
      "statusFinanceiro": "VALOR RECEBIDO CORRETO",
      "competencia": "2026-06-01",
      "observacoes": "Baixa registrada",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-24",
      "numero": "20260701252735",
      "cliente": "SANDRA EMIDIO DE SOUZA BOTTO",
      "cpf": "084.494.208-14",
      "banco": "NEO",
      "tabela": "NEO FLEX 4 - 37%",
      "produto": "Compra de Dívida",
      "valorOperacao": 46558.52,
      "valorLiquido": 17226.6524,
      "comissaoPrevista": 4888.6446,
      "valorRecebido": 0.0,
      "percentualComissao": 0.105,
      "diferenca": 0.0,
      "consultora": "GABRIELA",
      "dataDigitacao": "2026-07-01",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-25",
      "numero": "20260701252794",
      "cliente": "IRIS CRISTINA REBELO ARAUJO",
      "cpf": "106.660.523-87",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 5531.83,
      "valorLiquido": 5531.83,
      "comissaoPrevista": 1576.57155,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "ERICA",
      "dataDigitacao": "2026-07-01",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-26",
      "numero": "20260701252837",
      "cliente": "ROSELI EDITE DOS SANTOS",
      "cpf": "077.351.338-80",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 24866.36,
      "valorLiquido": 24866.36,
      "comissaoPrevista": 7086.9126,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-07-01",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-27",
      "numero": "20260702253259",
      "cliente": "ROBERTO DE OLIVEIRA PEREIRA",
      "cpf": "164.160.938-98",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 27475.98,
      "valorLiquido": 27475.98,
      "comissaoPrevista": 7830.6543,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "KALYTA",
      "dataDigitacao": "2026-07-02",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-28",
      "numero": "20260702253236",
      "cliente": "SCHEILLA ROSEMARY DE TOLEDO DA SILVA",
      "cpf": "139.299.208-75",
      "banco": "NEO",
      "tabela": "NEO FLEX 2 - 67%",
      "produto": "Compra de Dívida",
      "valorOperacao": 20086.69,
      "valorLiquido": 13458.0823,
      "comissaoPrevista": 4117.77145,
      "valorRecebido": 0.0,
      "percentualComissao": 0.205,
      "diferenca": 0.0,
      "consultora": "ERICA",
      "dataDigitacao": "2026-07-02",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    },
    {
      "id": "planilha-compra-29",
      "numero": "20260703253713",
      "cliente": "ANDRE ANTONIO DE ARAUJO",
      "cpf": "351.887.583-34",
      "banco": "NEO",
      "tabela": "NEO NORMAL - 100%",
      "produto": "Compra de Dívida",
      "valorOperacao": 19609.16,
      "valorLiquido": 19609.16,
      "comissaoPrevista": 5588.6106,
      "valorRecebido": 0.0,
      "percentualComissao": 0.285,
      "diferenca": 0.0,
      "consultora": "",
      "dataDigitacao": "2026-07-03",
      "dataPagamento": "",
      "dataRecebimento": "",
      "status": "Aguardando pagamento",
      "statusFinanceiro": "AGUARDANDO PAGAMENTO",
      "competencia": "2026-07-01",
      "observacoes": "Aguardando baixa",
      "origem": "Planilha Compra"
    }
  ],
  "clients": [
    {
      "id": "cliente-planilha-1",
      "nome": "DANIELA PAULA DE ARRUDA ALVES SIQUEIRA",
      "cpf": "152.983.318.31",
      "telefone": "",
      "vendedora": "RAISSA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-2",
      "nome": "MATHEUS PEREIRA DE SOUZA",
      "cpf": "379.097.668-74",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-3",
      "nome": "JULIANA GOMES MIGUEL",
      "cpf": "364.906.178-38",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-4",
      "nome": "MARIA DA CONCEIÇÃO DOS SANTOS SILVA",
      "cpf": "093.625.214-66",
      "telefone": "",
      "vendedora": "RAISSA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-5",
      "nome": "THAIS MAIA DA SILVA",
      "cpf": "405.776.018-06",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-6",
      "nome": "VERONICA DULCINEIA BACHA MOTTA",
      "cpf": "141.363.158-48",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-7",
      "nome": "RAMON DOS SANTOS DE MORAIS",
      "cpf": "424.040.908-01",
      "telefone": "",
      "vendedora": "VINICIUS",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-8",
      "nome": "CARLOS ROBERTO DA SILVA",
      "cpf": "059.463.698-14",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-9",
      "nome": "RICARDO CLEMENTE VERISSIMO DA SILVA",
      "cpf": "222.020.968-76",
      "telefone": "",
      "vendedora": "RAISSA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-10",
      "nome": "AGUINALDO FERREIRA DA SILVA",
      "cpf": "131.148.568-61",
      "telefone": "",
      "vendedora": "RAYANE",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-11",
      "nome": "MARCIA ROCHA",
      "cpf": "127.567.358-92",
      "telefone": "",
      "vendedora": "GABRIELA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-12",
      "nome": "MARIO MANOEL DE MELO",
      "cpf": "267.114.228-56",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-13",
      "nome": "LUIZ ALBERTO TAVARES",
      "cpf": "306.906.948-73",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-14",
      "nome": "ANDREA LAVORATO DOS SANTOS",
      "cpf": "153.658.528-93",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-15",
      "nome": "GILBERTO ALVES",
      "cpf": "196.530.968-26",
      "telefone": "",
      "vendedora": "VALDENIA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-16",
      "nome": "VICTOR SIQUEIRA DE MENEZES SANTOS",
      "cpf": "402.980.848-48",
      "telefone": "",
      "vendedora": "RAISSA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-17",
      "nome": "MARIA HELENA DE SOUZA",
      "cpf": "110.780.638-00",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-18",
      "nome": "ANDRE LUIS DE GOES",
      "cpf": "068.059.558-90",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-19",
      "nome": "CESAR MANOEL DOS REIS",
      "cpf": "078.735.988-29",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-20",
      "nome": "MARISA APARECIDA SANTANA LOPES",
      "cpf": "049.633.878-16",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-21",
      "nome": "SANDRA EMIDIO DE SOUZA BOTTO",
      "cpf": "084.494.208-14",
      "telefone": "",
      "vendedora": "GABRIELA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-22",
      "nome": "IRIS CRISTINA REBELO ARAUJO",
      "cpf": "106.660.523-87",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-23",
      "nome": "ROSELI EDITE DOS SANTOS",
      "cpf": "077.351.338-80",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-24",
      "nome": "ROBERTO DE OLIVEIRA PEREIRA",
      "cpf": "164.160.938-98",
      "telefone": "",
      "vendedora": "KALYTA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-25",
      "nome": "SCHEILLA ROSEMARY DE TOLEDO DA SILVA",
      "cpf": "139.299.208-75",
      "telefone": "",
      "vendedora": "ERICA",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    },
    {
      "id": "cliente-planilha-26",
      "nome": "ANDRE ANTONIO DE ARAUJO",
      "cpf": "351.887.583-34",
      "telefone": "",
      "vendedora": "",
      "produto": "Compra de Dívida",
      "status": "Ativo",
      "origem": "Planilha Compra"
    }
  ],
  "clt": [
    {
      "id": "CLT-001",
      "competencia": "2026-06-01",
      "consultora": "ANA LAURA",
      "producao": 7850.2,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-002",
      "competencia": "2026-06-01",
      "consultora": "MARIA",
      "producao": 14205.99,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-003",
      "competencia": "2026-06-01",
      "consultora": "RAYANE",
      "producao": 15351.55,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-004",
      "competencia": "2026-06-01",
      "consultora": "RAQUEL",
      "producao": 7336.51,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-005",
      "competencia": "2026-06-01",
      "consultora": "GABRIELA",
      "producao": 19516.99,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-006",
      "competencia": "2026-06-01",
      "consultora": "VALDENIA",
      "producao": 13919.19,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-007",
      "competencia": "2026-06-01",
      "consultora": "RAISSA",
      "producao": 1543.2,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-008",
      "competencia": "2026-06-01",
      "consultora": "KALYTA",
      "producao": 6164.78,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-009",
      "competencia": "2026-06-01",
      "consultora": "ERICA",
      "producao": 4533.77,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-010",
      "competencia": "2026-06-01",
      "consultora": "ANA CAROLINA",
      "producao": 0.0,
      "observacoes": "Lançar CLT do mês",
      "status": "PENDENTE",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-011",
      "competencia": "2026-06-01",
      "consultora": "DYOVANNA",
      "producao": 0.0,
      "observacoes": "Lançar CLT do mês",
      "status": "PENDENTE",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    },
    {
      "id": "CLT-012",
      "competencia": "2026-06-01",
      "consultora": "VINICIUS",
      "producao": 710.43,
      "observacoes": "Lançar CLT do mês",
      "status": "LANÇADO",
      "mes": "jun./2026",
      "origem": "Planilha CLT"
    }
  ],
  "settings": {
    "metaEmpresa": 1800000,
    "neoTables": [
      {
        "tabela": "NEO NORMAL - 100%",
        "percentualComissao": 0.285,
        "percentualLiquido": 1.0,
        "observacao": "Tabela normal"
      },
      {
        "tabela": "NEO FLEX 1 - 82%",
        "percentualComissao": 0.245,
        "percentualLiquido": 0.82,
        "observacao": "Flex 1"
      },
      {
        "tabela": "NEO FLEX 2 - 67%",
        "percentualComissao": 0.205,
        "percentualLiquido": 0.67,
        "observacao": "Flex 2"
      },
      {
        "tabela": "NEO FLEX 3 - 52%",
        "percentualComissao": 0.165,
        "percentualLiquido": 0.52,
        "observacao": "Flex 3"
      },
      {
        "tabela": "NEO FLEX 4 - 37%",
        "percentualComissao": 0.105,
        "percentualLiquido": 0.37,
        "observacao": "Flex 4"
      },
      {
        "tabela": "NEO FLEX 5 - 17%",
        "percentualComissao": 0.045,
        "percentualLiquido": 0.17,
        "observacao": "Flex 5"
      }
    ],
    "sellers": [
      {
        "nome": "ANA LAURA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "MARIA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "RAYANE",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "RAQUEL",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "GABRIELA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "VALDENIA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "RAISSA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "KALYTA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "ERICA",
        "clt": "SIM",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "ANA CAROLINA",
        "clt": "NÃO",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "DYOVANNA",
        "clt": "NÃO",
        "compra": "SIM",
        "meta": 30000.0
      },
      {
        "nome": "VINICIUS",
        "clt": "NÃO",
        "compra": "SIM",
        "meta": 30000.0
      }
    ]
  },
  "summary": {
    "proposalCount": 26,
    "clientCount": 26,
    "cltCount": 12
  }
} as const;
